services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: example1_student
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    ports:
      - "543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spring-app:
    build: .
    container_name: spring-app
    restart: always
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/example1_student
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root123
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
